apiVersion: v1
data:
    dburl: ENC[AES256_GCM,data:fLfhT4f22/1TsoDSRkrhc1vUvZ/LzMB+L/fekQj4Xv7jBNYDqY1HUNX6moFng3zq5pEiJJLup1p3QdawhhLYVgSFv/q6QvE7BKXrtVwBbHL1hM2B5tZODhd5c3TfelYEwSos+RixESq+MUPDvRhFGTtHiEC0IgG7qMqRPFNrRF0gqN128H+QcQ==,iv:0ZqEsCRCItY0w3Gy05tMuxDdMytv+FBmciKFohB/DNY=,tag:qhWrHGbuMDPrWOKkf/S8pQ==,type:str]
    password: ENC[AES256_GCM,data:acYUun6qjKeDQzlMrzR9jA==,iv:Bz02jO1RKD7wDl6Ko2QADY5MHXao0YNeFlloF3bXS1Y=,tag:vdYhy2f8b+MIdRsE92vWVw==,type:str]
    postgres-password: ENC[AES256_GCM,data:lEq+cCHJtmUzGDIi0kH+1Q==,iv:OJ4o3TmQH+OIqsuA1f/W0cUl9B1T8AohOJcsFecK7Zo=,tag:qnQ//OR8dxWZLKUlS93v5Q==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: coder
    namespace: coder-db
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-07-14T21:47:11Z"
    mac: ENC[AES256_GCM,data:ZlYDw+KJOaAtShTCN9DUfkpS9x4WNjTrLNfxWxWoUJPSEn7pD6X+rs3dQIt9TM1RFgqgZKjgOZ6ZS/sTX4Ou5Lu6Xcb2IMsKUeaUKX7Hm9DHUwi4uIVkPSaolmbpoG/q0qBSB+l6u072M+80yZ7TgRJlunmmO9HfjR60ZWNtPKo=,iv:tuDWGbXQGkFnC1qCY9BllqbzVvBGs91wYg3TxYAYl98=,tag:Klx73t8wCJiE6CYZqXmpUQ==,type:str]
    pgp:
        - created_at: "2023-07-14T21:47:11Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAx4MM/7fP/y8AQ/+Lnrj90MCH/Cb15yveutEn1qIhCb+SrggELp7N/C4iUb+
            RM0tUO3wOEGBw7C3jc2AZSIpqbBpXPKkYWXWbYWIIZPq2SgN3wTZy2TFpsfhsgwr
            N++/gXd51odNt5tQQ/PvPetLpamWOoKbrlF8kHGqs+RswgqXePOwCVhA9MlxQxe0
            UHuUHwJThv3wt/U5RsYKvdOwYYF9LS6p9wuxJWtPbcIbR/eyZIqSY9kE4hinuXTY
            9rjscxI0apRzxDYEJItOEV018PYDZnSzmn4pG+/IEjudLo0pZCCwlyDecdXFqCXm
            nN5ihoOs8yiXcE2mJAYrn06BNfy7IPMXazCmCq8TdUBOycne3qJMmRVgE1MJ2Q+G
            TesAhJZ3BDEFgAFmNNPX/SKrSC8OqsW5iTKu2t/g71S9CKwZyOqa01NbSLkRrQ2p
            jN654laEDMdtuxKgOsN8qgycb3qs3W8JaN2PmwJ7m2ABS8MZWCc4A/XemO4sdvsZ
            U0yov6fSbfXtQq0qS8kXUNaVsS52thEGMNmn4q6mtJQnJNvFK21xzUSv739UpbvM
            7Dsyat9sG0l57gmy8kMytMrhl5285fVTVCD+NWFOR2e0QFB4yFGBY39nyB2Qjdq2
            ZQejxAOTxCqqPtJ9fqHYk5tyRRpKsT4GNgQrLKOQEGAsNd3x4XN/egojbrixWRjU
            aAEJAhCceUxo9clYC0CJgndclwufMW9mB+1uuz8hSYsrbTC7kwDYue/IjHVNHjQT
            RpLUoz2zoro7fr5mNTuL8NvlqaLWGcs2grId7Zr18HOlWx47zyjB812rrFR4TrmV
            wTRrb4w/i/FT
            =C3Ee
            -----END PGP MESSAGE-----
          fp: 1EE79B3DA3C67B0204A9CDA39100B3510A99E0DC
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
