---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
# https://fluxcd.io/flux/components/helm/helmreleases/#specification
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: "1.4.2" # Had issues with 1.5.0!
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      interval: 12h
  targetNamespace: longhorn
  storageNamespace: flux-system
  maxHistory: 10
  install:
    createNamespace: true
  # https://github.com/longhorn/charts/blob/v1.5.x/charts/longhorn/values.yaml
  values:
    ingress:
      enable: true
      host: longhorn.sharing.io
      annotations:
        kubernetes.io/ingress.class: nginx
    # enablePSP: true
    # namespaceOverride: "longhorn"
    # kubernetes.io/tls-acme: true
    # tls: true
    # tlsSecret: wildcard-tls
  # values:
