# tunneld-wg-svc.yaml
# Wireguard service with reserved IP via Cilium L2 announcements
apiVersion: v1
kind: Service
metadata:
  name: tunneld-wg
  namespace: coder
  annotations:
    # Request specific IP from Cilium LB IPAM
    io.cilium/lb-ipam-ips: "${WIREGUARD_IP}"
spec:
  type: LoadBalancer
  loadBalancerIP: ${WIREGUARD_IP}
  internalTrafficPolicy: Cluster
  ipFamilyPolicy: SingleStack
  ports:
    - port: 54321
      protocol: UDP
      name: wg
      targetPort: 54321
  selector:
    app: tunneld
