# tunneld-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tunneld
  namespace: coder
  labels:
    app: tunneld
    app.kubernetes.io/name: wgtunnel
    app.kubernetes.io/component: tunneld
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: tunneld
      app.kubernetes.io/name: wgtunnel
      app.kubernetes.io/component: tunneld
  template:
    metadata:
      labels:
        app: tunneld
        app.kubernetes.io/name: wgtunnel
        app.kubernetes.io/component: tunneld
    spec:
      containers:
        - name: tunneld
          envFrom:
            - configMapRef:
                name: coder-config
            - secretRef:
                name: coder-config
            - secretRef:
                name: coder-override
                optional: true
          image: ghcr.io/ii/tunneld:0.1.10-sharing
          ports:
            - name: api
              protocol: TCP
              containerPort: 12345
              hostport: 12345
            - name: wg
              protocol: UDP
              containerPort: 54321
              hostport: 54321
