---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 1m0s
  dependsOn:
    - name: cluster-config
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/bases/controllers
  prune: true
  wait: true
  timeout: 1m0s
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
