---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: technitium-data
  namespace: dns
  labels:
    app.kubernetes.io/name: technitium
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # Uses default storage class (Longhorn)
