---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 1m
  url: https://charts.jetstack.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  # We install the namespace with the secret
  install:
    createNamespace: false
  interval: 1m
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: cert-manager
      version: 1.14.4
  values:
    installCRDs: true
    global:
      logLevel: 6
    extraArgs:
      - --enable-certificate-owner-ref=true
      - --dns01-recursive-nameservers-only
      - --dns01-recursive-nameservers=${nameserver}:53,1.1.1.1:53,8.8.8.8:53
