---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ot-helm
  namespace: redis-operator
spec:
  interval: 1m
  url: https://ot-container-kit.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: redis-operator
  namespace: redis-operator
spec:
  # We install the namespace with the secret
  install:
    createNamespace: false
  interval: 1m
  releaseName: redis-operator
  chart:
    spec:
      chart: redis-operator
      sourceRef:
        kind: HelmRepository
        name: ot-helm
      version: 0.18.3
