---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: capi-operator
  namespace: flux-system
spec:
  interval: 1m
  path: ./flux/bases/controllers/capi-operator
  dependsOn:
    - name: cert-manager
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
