---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-system
  namespace: flux-system
spec:
  interval: 1m
  path: ./flux/bases/controllers/kube-system
  prune: false  # Don't prune - we're only adding/patching, not owning kube-system
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
