---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: reflector
  namespace: flux-system
spec:
  interval: 1m
  path: ./flux/bases/controllers/reflector
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
