---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cnpg-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/controllers/cnpg-system
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
