---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kube-fledged
  namespace: flux-system
spec:
  interval: 1m
  path: ./infrastructure/controllers/kube-fledged
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
