---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kube-system
  namespace: flux-system
spec:
  interval: 1m
  path: ./infrastructure/controllers/kube-system
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  # postBuild:
  #   substituteFrom:
  #     - kind: Secret
  #       name: rfc2136dnsserver
