---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/controllers/longhorn
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  # postBuild:
  #   substituteFrom:
  #       # NOTE: contains the value "domain" but we may need or like
  #       #       to swap it out for a Secret which makes more sense
  #     - kind: Secret
  #       name: rfc2136dnsserver
