---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: ingress-nginx
spec:
  secretName: wildcard-tls
  dnsNames:
    - "${domain}"
    - "*.${domain}"
    - "*.${CODER_WILDCARD_DOMAIN}"
    - "*.${TUNNELD_WILDCARD_DOMAIN}"
  issuerRef:
    # name: letsencrypt-staging
    name: letsencrypt-rfc2136
    kind: ClusterIssuer
    group: cert-manager.io
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "authentik,coder,flux-system,longhorn,powerdns,kubevirt-manager,hh,registry"  # Control destination namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true" # Auto create reflection for matching namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "authentik,coder,flux-system,longhorn,powerdns,kubevirt-manager,hh,registry" # Control auto-reflection namespaces
