---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: configs
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/configs
  dependsOn:
    - name: infrastructure
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: Secret
        name: rfc2136dnsserver
      - kind: ConfigMap
        name: coder-kustomize
