---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coder
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: coder
  releaseName: coder
  storageNamespace: flux-system
  chart:
    spec:
      chart: coder
      version: "${CODER_VERSION}"
      sourceRef:
        kind: HelmRepository
        name: coder
        namespace: flux-system
      interval: 12h
  values:
    coder:
      podAnnotations:
        ii/config-hash: "${confighash}"
      envUseClusterAccessURL: false
      env:
      #  https://github.com/coder/coder/blob/v2.8.5/helm/coder/templates/service.yaml#L32-L49
      # We do not support `valueFrom` for this env var specifically
        - name: CODER_PROMETHEUS_ENABLE
          value: "true"
        - name: CODER_ACCESS_URL
          value: "${CODER_ACCESS_URL}"
      envFrom:
      - configMapRef:
          name: coder-config
      - secretRef:
          name: coder-config
      - configMapRef:
          name: coder-override
          optional: true
      - secretRef:
          name: coder-override
          optional: true
      service:
        type: ClusterIP
        externalTrafficPolicy: Local
      ingress:
        enable: false
        host: "${CODER_HOST}"
        wildCardHost: "*.${CODER_WILDCARD_DOMAIN}"
        # This ingress part of the chart needs wildcard love!
        className: nginx
        tls:
          enable: true
          secretName: coder-wildcard-tls
          wildcardSecretName: coder-wildcard-tls
        service:
          type: ClusterIP
        annotations:
          nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
          # https://www.nginx.com/blog/websocket-nginx/
          # https://kubernetes.github.io/ingress-nginx/user-guide/miscellaneous/#websockets
          nginx.ingress.kubernetes.io/server-snippets: |
            location / {
            proxy_set_header Upgrade $http_upgrade;
            proxy_http_version 1.1;
            proxy_set_header X-Forwarded-Host $http_host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header Host $host;
            proxy_set_header Connection "upgrade";
            proxy_cache_bypass $http_upgrade;
            }
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: coder-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: coder
    namespace: coder
