apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-repo.yaml
  - helm-release.yaml
  - ingress.yaml
  - ingress-default.yaml
  - ingress-default-quick.yaml
  - ingress-demo.yaml
  - create-admin-job.yaml
