apiVersion: v1
data:
  ghost-password: RWVnYWl4aWVCaWVxdTBxdQ==
  mysql-password: VWVuZ2VvNnJvZ2hhZ2hlaQ==
  mysql-root-password: VWVuZ2VvNnJvZ2hhZ2hlaQ==
  smtp-password: czVzZXhwbGU3anNzZGR0NA==
kind: Secret
metadata:
  creationTimestamp: null
  name: ghost-passwords
  namespace: ghost
