apiVersion: v1
data:
    ghost-password: ENC[AES256_GCM,data:kaYyLZARZEwRomuI,iv:qFCZc6i51i9lh/724urrRKk2xR+LhE9AgTu0nF7H3yY=,tag:WO0AkfxuViFfJ8/sNRW9cw==,type:str]
    mysql-password: ENC[AES256_GCM,data:6Rc25efvd4gFtepmNV86uL7NH8ww7vF8,iv:i5avDgyhCckzC3BsOt3Ms6yYJUZMOaJb+elFfiAVSoc=,tag:zRATmaOrfl6agjq6qIdmrw==,type:str]
    mysql-root-password: ENC[AES256_GCM,data:+n+mPJX7OGdMmQIDSAkLgam7NGR+5vah,iv:nDvkpX+HE8IyqMKmJNWXFCLT5MyvVlwNM53IWRfyPF0=,tag:A8YG6oGYBUKZOkuBH/+agg==,type:str]
    smtp-password: ENC[AES256_GCM,data:PDavUSoPGhgKIdwhxd1hcJqayKNtMIbt,iv:aZa4ovRFA8BQ4la/owbpwDTwSHRYKkToz+b4mVGhkAI=,tag:gEi3cRmpqx8mF3Dp4k56tA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: ghost-passwords
    namespace: ghost
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-07-15T08:29:16Z"
    mac: ENC[AES256_GCM,data:Sf6Fi67ZWwTHMuXObZkgwA6FWsPsctMWC9+dKVcwz7cZ3+QCi/3CyziWC74fGm6/1v7DV7VL9VCqWgHJX5HW0nW0LRK4GhhiaADoZRK+ONGSRYjmsqaEz1U6D71w9qL0SS51VjDP3CbSGsY9giLXaag6LV4K2F8lCSxpicxj+Ao=,iv:LU8DxNNNT4sThGcY8hdMn3Za/JTdbiwxerfs3J68TPs=,tag:ziar4C9gstt3GHxz3qmW7g==,type:str]
    pgp:
        - created_at: "2023-07-15T08:29:15Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAx4MM/7fP/y8ARAAjjj7tPMduReRk+KxU5IxbfUaTjhv/1DxsQzO8TaOOQbP
            S9fIyawn/6DdUMd6pGvjp8lj85iMmoZ6Gfx7YeqIsxP/1eFYJkxZioclbXpY3HwO
            ei+9oBDjuiYd42nodi4H3U6uK62z0td3L8suLE5c50zVCoUAb2g/+guZ/RwfgNJC
            xGARWdK/DAR+WnANan1QE9rlCcIVYLaWEtLUEyxYaxXI/7phUeXYIlJt5cloCuq8
            2HIusjs22zHdIvhwRSlGQB3ENUFumdIgNugPP9mPKOUsS8izXpme7r95uZIAkqHj
            6ZukvHImwXrBcyp333SztYBKL6Tbabd4NX/W1lb4UfJAgPTOfFFXNTYQtwo/Cz+U
            /uQ3yMYoB1D1YahqPfhtnI2IOiFyC8qfbcVOCMdtLtO8GVy6X5NBtjHhW3GbfXFE
            kF9Qbcl1kIqUNwvfOVRrl7o00aEr6hBYXztDFiXqDT/L0f9e5ymg0PPB9sIIXrC2
            EhFXSgE3mxHcz9T9HKt33F+aBkNSa+8pcJ2Hvw+JnZAN0/hAcm3v5Au0+AvlgkEd
            72jzp2/BJy9jpIZ3erb/GFdqvSeNdo5Ashgb+IBz6ySodQLoCyMAh/++gZWHlgMA
            32l1IGBnAIEIZYMesmPpnnCnSKx8vFPPqmxvYp69WOhEgoEG6rhnPI7goRf723nU
            aAEJAhBN5w6kvkDBWZ7vVc4MS9wYAHFxd5IimVVhZYbHDU4puqoxqw0vzlgQ4WEx
            DaxriZgubln0qF291VSjtcAj0AHqIZ1/0IaNWBQ2Wc9m4t2gCIFALusExG73tfvv
            LvYE/JF0/pOt
            =aCGv
            -----END PGP MESSAGE-----
          fp: 1EE79B3DA3C67B0204A9CDA39100B3510A99E0DC
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
