apiVersion: v1
data:
    ghost-password: ENC[AES256_GCM,data:0VqmzYMInjv15zsLjfR/6HEYhB50db1l,iv:cmhpYwptKGWRpL09dZxO0QeGPu8CMJukNXQ+3Wsm0Q0=,tag:JAe9JOsPY83fIYKkgEaINQ==,type:str]
    mysql-password: ENC[AES256_GCM,data:D6BUUp/km0Jy91YX/xryye1q+WoybrSE,iv:ltnBENq0VpvkGluOR8LLPwbKikhg9VJBi06hgjbtQn0=,tag:jxYIcMpVFqyUbCcU5KwHQw==,type:str]
    mysql-root-password: ENC[AES256_GCM,data:0FbjRvXcVvZZJn0uc67tDDBNlvJ1qLF2,iv:ZJrPa/n5UsuBV4R90daJSQBzw6mASYXDtlDjNgNOTH8=,tag:xZzHhm6hnje76INbnkuRLw==,type:str]
    smtp-password: ENC[AES256_GCM,data:ClgdY9jmTIjvmd2I03JSUJQaiuyuCBRf,iv:ONRDC5uMuKc3dJxwdV3sBYFKMI4yjF8aI/LlKCH0oUU=,tag:EM2Ajk8qIYLEADbmxRBZ5A==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: ghost-passwords
    namespace: ghost
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-07-15T08:57:08Z"
    mac: ENC[AES256_GCM,data:2CTtdrrs658fPIJlO2Se3dTbttjv1VxA1VU3u0IxR/9lBDOS4MY3W7mJLBfZRAlAqReTVQZ5WAloCMXPOefnHchRQ992GUAeWfJolD2Z0obZoZAv9fHRle7jlTOPeUq08HKFrSxavIFEiy9HJ70OAdaQrqNJKAf2X2/mZGjUvlw=,iv:JeHsw/7exNwg+BbwvbDFfmcMF0If34ujMs+2fRPgquM=,tag:fIMI6Q0w8BIleb934QAZvA==,type:str]
    pgp:
        - created_at: "2023-07-15T08:57:08Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAx4MM/7fP/y8AQ/8Cg0oeela8+F2dxCIWOx0PNYmAE5hhhk7xQlKjlhSMCU9
            6mlXgmi7B0OvEZQr9swwe9DOkTbXH7KbBrUbXodd3BM32aOvCNio+20YJrJEniOa
            QN6VJewLw1+mMlR03MKnj6UntmMVXVBa76eJN+xmWAsGhS0yZmN311orO0tbvqzj
            PJR6db2eJhTrWW4WVDjlqShS7uwC1jamEudW1/IFCFR9tv4aWLObfq0y1QomJ9cD
            SddsZqRrk2L287oK8RnCEhzgFU/4NCT7f3u1YMbKn0//oxJbKUKB8POVA3JMpzLV
            qmfdOmSf5v/MSW7beiPSqQPmorxxyBUKATZj5JlAPqtwZuJpDSHKYtqtgQnL1Xcy
            vWcwcWy18TGZsbrEc8egAHjWdrTkQzWOxFBy8cYybmhw4WL/TFxzig1sV4CHCp19
            t1Ej6NPL+h6hW2LaUPwXSPJhbwWbgA7z94oshSAsdEG6G+ldJNUm6EUldTUwdm48
            a0B5zQkApURjldSzuX2RZjubWIHL830qNRMDEv77vFTYU0YFzx+ZK9e2FbvDbHB7
            JrreadIP1rSiIoEpEl1NEyA2qCyXvyJLXzpWo9wDsW7YnoXcCvztxVKxAlmgGqnr
            St90W2HwHSDXJuGJJCh9rJpt12NLvusyO/jn/6WWUU8GfwYi0iZvrL4/1cFvOFTU
            aAEJAhDG9VgP3yTMPaHn+ZQrAb1bcfKCiLS9MlGsesS6Br0e41I+eoHdzqX4fOxo
            9BfuJAZJCPLS96lct9z2Go5zn4Lbx3PJJBDU7WiedElawLWrHSCQS5hx+ZyDzZCM
            7S/YBGO81CwI
            =fuJs
            -----END PGP MESSAGE-----
          fp: 1EE79B3DA3C67B0204A9CDA39100B3510A99E0DC
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
