---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ghost
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: ghost
  storageNamespace: flux-system
  install:
    disableWait: true
    # createNamespace: true
  upgrade:
    disableWait: true
  chart:
    spec:
      chart: "ghost"
      version: "19.3.23" # 5.54.0" # Current as of Jul 12, 2023
      sourceRef:
        # bitnami was depoyed with coder
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 12h
  values: # https://github.com/bitnami/charts/blob/main/bitnami/ghost/values.yaml
    global:
      # storageClass: "ceph-filesystem"
      storageClass: "longhorn"
    extraEnvVars:
      - name: LOG_LEVEL
        value: DEBUG
      - name: GHOST_SMTP_PASSWORD
        valueFrom:
          secretKeyRef:
            name: ghost-passwords
            key: smtp-password
      - name: GHOST_ENABLE_HTTPS
        value: yes
      - name: GHOST_HOST
        value: abcs.news
      - name: ALLOW_EMPTY_PASSWORDS
        value: no
    image:
      registry: docker.io
      repository: bitnami/ghost
      tag: 5.53.2-debian-11-r0
      # debug: false
    ghostUsername: "chris"
    ghostEmail: "chris@mcclimans.net"
    ghostBlogTitle: "ABCS News"
    ghostEnableHttps: false
    ghostHost: "abcs.news"
    ghostPath: "/"
    existingSecret: "ghost-passwords"
    smtpExistingSecret: "ghost-passwords"
    smtpHost: "smtp.fastmail.com"
    smtpPort: "465"
    smtpUser: "chris@mcclimans.net"
    smtpProtocol: "ssl"
    # ghostHost: "abcs.news"
    persistence:
      enabled: true
      # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes
      accessModes:
        - "ReadWriteMany"
      size: 10Gi
    mysql:
      auth:
        existingSecret: "ghost-passwords"
      primary:
        persistence:
          enabled: true
          size: 20Gi
          # storageClass: ceph-filesystem
          storageClass: longhorn
          accessModes:
            - "ReadWriteMany"
    ingress:
      enabled: false
      hostname: "abcs.news"
      tls: false
      extraHosts: "ghost.abcs.news"
      ingressClassName: "nginx"
      # https://github.com/bitnami/charts/blob/main/bitnami/ghost/templates/tls-secrets.yaml#L8-LL24
      secrets:
        # Seems to require:
        # .name
        # .certificate
        # .key
        - name: "abcs.news-tls"
          certificate: "CAN WE JUST USE EXISTING SECRET"
          key: "RATHER NOT PUT KEY HERE"
    service:
      type: ClusterIP
