---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ghost
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: ghost
  storageNamespace: flux-system
  install:
    disableWait: true
    # createNamespace: true
  upgrade:
    disableWait: true
  chart:
    spec:
      chart: "ghost"
      version: "19.3.23" # 5.54.0" # Current as of Jul 12, 2023
      sourceRef:
        # bitnami was depoyed with coder
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 12h
  valuesFrom:
    - kind: ConfigMap
      name: ghost-values
