---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: coder
  namespace: flux-system
spec:
  interval: 5m
  path: "./coder"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: coder-db
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  # healthChecks:
  #   - apiVersion: networking.k8s.io/v1
  #     kind: Ingress
  #     name: hubble
  #     namespace: kube-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: coder-db
  namespace: flux-system
spec:
  interval: 5m
  path: "./coder-db"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: coder-coder-db-postgresql
      namespace: coder
