---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ghost
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./ghost
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  postBuild:
    substitute:
      LOG_LEVEL: DEBUG
      GHOST_HOST: abcs.news
      GHOST_BLOG_TITLE: "ABCS of the World"
      GHOST_USERNAME: "C"
      GHOST_EMAIL: "chris@mcclimans.net"
      GHOST_ENABLE_HTTPS: "true"
      # We use secrets for passwords
      GHOST_SMTP_HOST: "smtp.fastmail.com"
      GHOST_SMTP_USER: "chris@mcclimans.net"
      GHOST_SMTP_PROTOCOL: "ssl"
      GHOST_SMTP_PORT_NUMBER: "465"
  patches:
    - patch: |
        - path: /spec/template/spec/containers/0/env/
          op: add
          value:
            name: "ENV_DEPLOYMENT"
            value: "YES"
      target:
        kind: Deployment
        name: ghost-ghost
        namespace: ghost
# Comments
# - path: /spec/containers/0/env
#   op: add
#   value:
#     name: "GHOST_ENABLE_HTTPS"
#     value: "yes"
# - patch: |
#     - op: add
#       path: /spec/values/extraEnvVars
#       value:
#         name: "ENV_HR"
#         value: "yes"
#     - op: add
#       path: /spec/values/extraEnvVars
#       value:
#         name: "SETMYVAR"
#         value: "MYVALUE"
#   target:
#     kind: HelmRelease
#     name: ghost
#     namespace: flux-system
