apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Kustomizations
  - cert-manager.yaml
  - nginx.yaml
  - longhorn.yaml
  - cilium.yaml # just for incress for now
  - gitops.yaml
  - flux.yaml
  - coder.yaml
  - ghost.yaml
# components:
#   - ../../longhorn
#   - ../../nginx
#   - ../../cilium
