apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gitops-dashboard.yaml
  - receiver.yaml
  - receiver-token.yaml
  - pdns-tsig-key.yaml
  - cert-manager.yaml
  - nginx.yaml
  - longhorn.yaml
  # I'd prefer this load via components: - ../../cilium
  # - ../../cilium/hubble-ingress.yaml
components:
  # - ../../longhorn
  # - ../../nginx
  # - ../../cilium
