apiVersion: v1
data:
    key: ENC[AES256_GCM,data:I1YcgB7LGBRMq0hp1C8CJ6T8yIjdBzHliEgdJjfHbQKAKOomR+O4rO4vaAAC2vd+Qm8VNBrzB5+SrlNXnZywHMRmVKesL+FvaqdidZx6DflQ6jbf8ChSDFs7gwNx3+U50L86w6bUEldXGx13IpxxxVlRqDMdaKi0,iv:8Ul7ZgvrcAuHy79wfaJiIl75HrdU8aCEeZ97lGmPahI=,tag:EhhcsWsTvUoNYoOkYejyIw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: pdns
    namespace: cert-manager
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-07-14T15:44:41Z"
    mac: ENC[AES256_GCM,data:p7XiW71MarBOuTaZ+HdHCuDvkpiOb9pEKBneQFbF1jJNPoz0KQd2zj+2tbINt6AY7eibEpNRvZijHbs01bwKSFqbqbFXUjnQey0sSvcM7AFyzwPfcHoGRtStpPLj0UncuvKrzor4PesEutWBT/ts7g+dTdNcwfu+YtHa+Wfwbr0=,iv:ck1XMr+mVCa5zWgsdKNlEi6t75yu2ix23Oj8t8ZbLYU=,tag:TAXa6nhlieH042JGkl6SPw==,type:str]
    pgp:
        - created_at: "2023-07-14T15:44:41Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAx4MM/7fP/y8AQ/+MT2n6/SEeQQxMK9gYEc2AjbwK61wAy2c/KZPgadk/e7r
            Uw4eXREXecNBBoUYt8GevymX3LxuA91xbA7zbrSZaaY+x/hiGrOak4C0C0JO0n9N
            WyoFalZNGUTyp7yOc64HxiC8OfQBnamcJzqzHqVtWYBBvCuKlWQRbraSdQlbyG5j
            nVeCexL/3D6tHB3psK5KmkJrfLMOKj8ryCh74NatKPt0AEj35A/41EaeDvG7LSDH
            vG7e0LUnWHgeV14hguw6QX0nUezzprSYncoKLYdftx4fZHzhM0yun1g4nWqS/jaf
            1kdyRdrXoEggkjn6xYFHIkNQR2gfuJR8sRJXHiP12q+VzF/7zzMMfxXgy7q9VrI9
            wpjWF7xyZ9ipUkWq06JGC9unoL/UlT1m5tTACZa52HC/CGRarSQo4L2UAZwgmcwh
            M8Tsx16PxxgVsUGgz0rhDGw2OFs/880XfahxfcbdUbM/HaUZ28p9VCmzsveONYJQ
            gdB2ODhpJdVq02TjfqtdQnztRIqCqnFO/veRFrIxATdkFd/fapI0T+OeT3UZyaUv
            sVcUQ4hdfRgL40tCWvVv1nh9MKn0iX3V7KpEP6TyeZsjtsjscQmaGws96z+Kaz1S
            9DGQlqs4hpSOJsGAbBoHgUQ1cggwMpUzoViyw54xt6tKpPwcwIS40b7HVz0kewLU
            aAEJAhBWyoRroc6UEBKOJ/VQ809osMo12HqPGHMyd/PvQf3cM5zNH9VfqWusvwMH
            Aq7YaBVQWLLtMLhAug9DbxOnOV36t5ssr8BdUy5twDwy7Y/xlq/1sXO4hsvb0W96
            CMsOIoatAhRw
            =S6wZ
            -----END PGP MESSAGE-----
          fp: 1EE79B3DA3C67B0204A9CDA39100B3510A99E0DC
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
