---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: capi-operator
  namespace: flux-system
spec:
  interval: 30m
  install:
    createNamespace: true
  targetNamespace: cluster-api
  releaseName: capi-operator
  storageNamespace: flux-system
  chart:
    spec:
      chart: cluster-api-operator
      version: "0.10.1"
      sourceRef:
        kind: HelmRepository
        name: capi-operator
        namespace: flux-system
      interval: 24h
  values:
    logLevel: 4
    image:
      manager:
        image: registry.k8s.io/cluster-api/cluster-api-controller
        tag: v0.13.0
    manager:
      featureGates:
        ClusterResourceSet: true # https://kubevirt-manager.io/get_started.html
    bootstrap: talos
    controlPlane: talos
    infrastructure: kubevirt
    # addon:
    #   x: true
    # env:
    # manager:
    #   - name: FOO
    #     value: BAR
