apiVersion: kustomize.config.k8s.io/v1beta1 # <-- Kustomization API
kind: Kustomization
resources:
  - cluster-issuer.yaml
  # Cert will depend on cluster-issuer and other
  - cert.yaml
  - pdns-tsig-key.yaml
