apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-multus-ds
  namespace: kube-system
spec:
  template:
    spec:
      volumes:
      - hostPath:
          path: /etc/cni/net.d
        name: cni
      - hostPath:
          path: /opt/cni/bin
        name: cnibin
      - hostPath:
          path: /
        name: hostroot
      - configMap:
          items:
          - key: daemon-config.json
            path: daemon-config.json
          name: multus-daemon-config
        name: multus-daemon-config
      - hostPath:
          path: /run
        name: host-run
      - hostPath:
          path: /var/lib/cni/multus
        name: host-var-lib-cni-multus
      - hostPath:
          path: /var/lib/kubelet
        name: host-var-lib-kubelet
      - hostPath:
          path: /run/k8s.cni.cncf.io
        name: host-run-k8s-cni-cncf-io
      - hostPath:
          path: /var/run/netns/
        name: host-run-netns
      initContainers:
        - command:
            - /install-cni.sh
          image: ghcr.io/siderolabs/install-cni:v1.8.0
          securityContext:
            privileged: true
          name: install-cni
          volumeMounts:
            - mountPath: /host/opt/cni/bin/
              mountPropagation: Bidirectional
              name: cnibin
        - command:
          - sh
          - -c
          - |
            if [ ! -f /host/opt/cni/bin/multus-shim ]; then
              cp /usr/src/multus-cni/bin/multus-shim /host/opt/cni/bin/multus-shim;
            fi
          name: install-multus-binary
