---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: technitium
  namespace: flux-system
spec:
  interval: 1m
  path: ./flux/bases/apps/technitium
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-ips
      - kind: ConfigMap
        name: cluster-config
  dependsOn:
    - name: infrastructure
    # Note: certificates now depend on technitium, not the other way around
