apiVersion: v1
kind: Service
metadata:
  labels:
    app: containerized-data-importer
    app.kubernetes.io/component: storage
    cdi.kubevirt.io: cdi-uploadproxy
    operator.cdi.kubevirt.io/createVersion: v1.60.3
  name: cdi-uploadproxy-nodeport
  namespace: cdi
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    cdi.kubevirt.io: cdi-uploadproxy
  type: NodePort
