apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: sharingio
  name: sharingio
  namespace: sharingio
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 10.128.0.0/12
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: TalosControlPlane
    name: sharingio-control-plane
    namespace: sharingio
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
    kind: OCICluster
    name: sharingio
    namespace: sharingio
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: OCICluster
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: sharingio
  name: sharingio
  namespace: sharingio
spec:
  compartmentId: ocid1.compartment.oc1..aaaaaaaac5nbffbezgxubg53nem624gylmjihujtw4ypafwoxp3mvrmcu5ba
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: sharingio-control-plane
  namespace: sharingio
spec:
  controlPlaneConfig:
    controlplane:
      configPatches:
      - op: replace
        path: /machine/install
        value:
          bootloader: true
          disk: /dev/sda
          image: factory.talos.dev/installer/d01e4eb407f9a242831748cab07de55550fdcfe8be65ce4defd258a93d94562f:v1.7.6
          wipe: false
      - op: add
        path: /machine/kubelet/extraArgs
        value:
          cloud-provider: external
          provider-id: oci://{{ ds["id"] }}
      - op: add
        path: /cluster/apiServer/extraArgs
        value:
          cloud-provider: external
      - op: add
        path: /cluster/controllerManager/extraArgs
        value:
          cloud-provider: external
      - op: add
        path: /cluster/allowSchedulingOnMasters
        value: true
      generateType: controlplane
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
    kind: OCIMachineTemplate
    name: sharingio-control-plane
  replicas: 3
  version: v1.30.1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: OCIMachineTemplate
metadata:
  name: sharingio-control-plane
  namespace: sharingio
spec:
  template:
    spec:
      compartmentId: ocid1.compartment.oc1..aaaaaaaac5nbffbezgxubg53nem624gylmjihujtw4ypafwoxp3mvrmcu5ba
      imageId: ocid1.image.oc1.us-sanjose-1.aaaaaaaaqemyxu4dnhuapt6dfzuhq6rp5h3f7ld3yqh3crwiu5qtzlk6woma
      isPvEncryptionInTransitEnabled: true
      metadata:
        ssh_authorized_keys: ""
      networkDetails:
        assignPublicIp: true
        nsgIds:
        - ocid1.networksecuritygroup.oc1.us-sanjose-1.aaaaaaaagzhulfmzkzmcdc5hr33wfvpqmxeq2bgjs5inchmzoi6s7vhzlvjq
        subnetId: ocid1.subnet.oc1.us-sanjose-1.aaaaaaaan27lv43bzsga256p2im3iuwf5ktlbu7u56tmv4rb7zzuna3c5oaq
      shape: VM.Standard.A1.Flex
      shapeConfig:
        ocpus: "4"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: OCIMachineTemplate
metadata:
  name: sharingio-md-0
  namespace: sharingio
spec:
  template:
    spec:
      compartmentId: ocid1.compartment.oc1..aaaaaaaac5nbffbezgxubg53nem624gylmjihujtw4ypafwoxp3mvrmcu5ba
      imageId: ocid1.image.oc1.us-sanjose-1.aaaaaaaaqemyxu4dnhuapt6dfzuhq6rp5h3f7ld3yqh3crwiu5qtzlk6woma
      isPvEncryptionInTransitEnabled: true
      metadata:
        ssh_authorized_keys: ""
      shape: VM.Standard.A1.Flex
      shapeConfig:
        ocpus: "8"
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: TalosConfigTemplate
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: sharingio
  name: sharingio-md-0
  namespace: sharingio
spec:
  template:
    spec:
      configPatches:
      - op: replace
        path: /machine/install
        value:
          bootloader: true
          disk: /dev/sda
          image: factory.talos.dev/installer/d01e4eb407f9a242831748cab07de55550fdcfe8be65ce4defd258a93d94562f:v1.7.6
          wipe: false
      - op: add
        path: /machine/kubelet/extraArgs
        value:
          cloud-provider: external
          provider-id: oci://{{ ds["id"] }}
      - op: add
        path: /cluster/apiServer/extraArgs
        value:
          cloud-provider: external
      - op: add
        path: /cluster/controllerManager/extraArgs
        value:
          cloud-provider: external
      generateType: join
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: sharingio-md-0
  namespace: sharingio
spec:
  clusterName: sharingio
  replicas: 6
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: TalosConfigTemplate
          name: sharingio-md-0
      clusterName: sharingio
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        kind: OCIMachineTemplate
        name: sharingio-md-0
      version: v1.30.1
