---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: authentik
  namespace: flux-system
spec:
  interval: 1m
  path: ./infrastructure/apps/authentik
  dependsOn:
    - name: longhorn
    - name: configs
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: authentik-kustomize
      - kind: ConfigMap
        name: authentik-config-hash
