---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: coder-db
  namespace: flux-system
spec:
  interval: 1m
  path: ./infrastructure/apps/coder-db
  dependsOn:
    - name: longhorn
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: coder
  namespace: flux-system
spec:
  prune: true
  interval: 1m
  dependsOn:
    - name: coder-db
    - name: authentik
  path: "./infrastructure/apps/coder"
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: coder-kustomize
      - kind: ConfigMap
        name: coder-config-hash
