---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: technitium
  namespace: flux-system
spec:
  interval: 1m
  path: ./infrastructure/apps/technitium
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-ips
  dependsOn:
    - name: configs
