apiVersion: v1
data:
    dburl: ENC[AES256_GCM,data:IbZ9VwK/LHmiveEUo+h1iI1TAdM4YMrZtruDf0w1mwq7tk30O+CGIaDp1sOZZIzLVy2XGRlPJsk1fFR9Hgzbq7WYHNtxRDiJZtkBNmifbE2cRONidDeG7+yCV/h+esjjcu7hqckz5T2gMU0WW3j4RBG3R9YTHIr8KCI0omVGx5kAVkJii0XgZg==,iv:qiA7h55qxnrcmP1jwe/O/UF59VVRdNC+2matSv2+xIY=,tag:PRgaBbHFkZoDBlwJf7yYxg==,type:str]
    gitauth-id: ENC[AES256_GCM,data:HbF4YJ0AdENIA0tTVyibZEeT1ol/1dmPHijssg==,iv:HQSqHvuDZ6K9O0zK8wH2EoW28AbRqR/wpvMqZLIncSc=,tag:kiQwJEyrz4S3ZI75oIaBHA==,type:str]
    gitauth-secret: ENC[AES256_GCM,data:uoRWKDvsRSm0LBtVyLC9PLz1kNHWuz6nKrEfNLi5fDhImbQF9HLprPSo3i8IMij38PZ4/n/RK48=,iv:X7Msmarw99dzQ2sAJYGbn3V0Qw2tfYBJvrR58vgZJNE=,tag:zQYDzQ6TMYLs4IvF2TUwdA==,type:str]
    github-token: ENC[AES256_GCM,data:vBm5veAhFohvV1/k/17vxPlgkRjeecoiQ6vTWlmA9SeOvA2qz7RDj+BYYZvmLSJPrR9s/pLQuiMs01kfRXKgN5+Mwk7BnvHJNlJ1hUHVKOFJX76hmfRGA0cbplEtiHMX7c+ybtwp7+sRMbZcx2yHw4KaOSUxVgkMBe3a8g==,iv:gk/d8DMkHo9RDXMpN/XrluoxHg0fRiGiYtGzj4zObv8=,tag:klEFpVGBXHzibdV+vQ9Bqg==,type:str]
    metal-auth-token: ENC[AES256_GCM,data:D6LqrOZfNTetybCyKDHWkg1tucT9SrPh5j5uCUnitQilQpVBrLTtwyXm2w0=,iv:/34BoyQzFukKFPiQ+OldSycVgFDR6bnxz4Vg4TSRT54=,tag:qeTqKZznp+LrQtoCBf9VwQ==,type:str]
    oauth2-id: ENC[AES256_GCM,data:zBf3/GgvvEXbKRSEIHXa4DKWdL2WOnIhFx9JhQ==,iv:I4KGkRsHa/CCEYGDew1sk6/DYG9RF6Xri/9iISVlaME=,tag:uEDIGcsZLuSLH7BfPolaxg==,type:str]
    oauth2-secret: ENC[AES256_GCM,data:4kiOFssbgxTu6rJpvyZRAFM6YXuagm8sJvgxszVHhSCdvnq9U2gdhhb1fpjsFfQY6YGSlyi1BN8=,iv:XahoCXsB1dc1x8gXlyZZsIq8GoMtusk5tatTxROiNLU=,tag:S8D8C/D8PoFuyv4LFNPcQg==,type:str]
    password: ENC[AES256_GCM,data:geNPs9I9zbq3zVa18Ywacw==,iv:UczQGI6x5gdOEoN7b97hiGBOqjUiSkZdLwnUjaSXKhE=,tag:km673F6Z/p7dL2HssUc/dA==,type:str]
    pdns-api-key: ENC[AES256_GCM,data:hSdfHXSwQWnhtAPqNbm9b080VZ9pvjRV0x8jGA==,iv:04GftaZyRBzZq6KAl9N6o8jcruzr4wW8Z0UmU8No9sw=,tag:M+mUFMcneBu+Hz+cxBVjHw==,type:str]
    postgres-password: ENC[AES256_GCM,data:p+leoht+qHhP2G51rbfAsw==,iv:I2pd0RS6xXc0x0Ssz3j9B6kGgj7OZeRuVg8jwfgFXAE=,tag:DgKekSsk/clHtme4QctEoQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: coder
    namespace: coder
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-07-14T21:04:03Z"
    mac: ENC[AES256_GCM,data:8T/3UeBWNAI1HdSVt87I55BOtr8g4GXz8sSCNEsxzDf2QE0WppTnX4/GV7UzWhz28tJEUVI22A8/ebGgzpSoGVaHZwqR9pi8fWUKdeJ9VVYuCR8Arh6n5ReH3c3DoI2VB1c7Vt5MtjD1poElxfMFvCoQYbGLBPIq9GsmASokZ/E=,iv:mDZS32z45K7Wgwd1UWmNJ140KuTketW54BEcSEhGhuw=,tag:16ybRZXW3V+xwxdvTZXe2A==,type:str]
    pgp:
        - created_at: "2023-07-14T21:04:02Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAx4MM/7fP/y8AQ//ZrydMkNg6j2M5J2JBR2Afal81DHV0I62DrUlxVB7J5+8
            2co0TutJx8ZtTXCCCvaZ54J8D6FExoPqCC307wHK8RGNUD/+LmMiXBwf1LdAjkVd
            g/7BgI5AJOjU2Rj9hql9cOonwG2KXRFBBFYWVhWe7CQqj5WQTGl6Af9/q0+f3LSs
            9bpav3iQjNPqMcuOp9G5up8jWJQqL7Zx7lHpilaIG3Jb2ZBlr2iYTs/uiailUvQi
            uozDADQuxMHE++sbLcEVrnDw933RIPgn3o33O4rVVLzvv7nVq6LVdbGQhVp8fg4b
            zrGybynYyWhHzebZM5Z3jHpQNIKO39UOwCvUhWLPriorV5yXbGkhso+Z7YTvSbx9
            QPgPaFqG/FmJebaaDENSwUC4cWhegqgGrFOA39PfeEmeavbrZmCNdTOKkXtifzCH
            4Uj6do/LfjBn4ScxRaiCQZFMk3LTMVBURorZDvBzsRTr4HvjdJ3e1xTYdWnTw3yM
            apEXOnswDYo3yK+rJTatraQFhvLDn7UegZ754Nh5S35EWH1LyfcALu2tok/a6717
            FOrY1zqkxG5B3DY9HDE7pylSUKjw4X4YH4jrU680B4CTMDT2AeBcaQ4xvwudQly8
            CGekJpBrFZ1wXLMuR6feM+OuKBVaSMSz2lAxnW6v/Na/kchTvdFtUokwN3kP74DU
            aAEJAhBBELBfTlObo0RH1azM1i/KA6sgxIXCBBKxwkKvvB/STi1ne/rS4aUaumto
            n1abEw8D3mJCQfy/1G6l++wvDXsFo4HLx1OHiSEiaNZShVV4s01MJ5Tc2sY0afTZ
            QCnAuLGpqRIv
            =eRFW
            -----END PGP MESSAGE-----
          fp: 1EE79B3DA3C67B0204A9CDA39100B3510A99E0DC
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
