apiVersion: v1
data:
    dburl: ENC[AES256_GCM,data:IdnQBOVU2dtCtNSjvJwcAMcm4KzOw2NtRZpXH+aFNPz+YRZdVal/zOGM+VL/Ri6zwclKIlXS9ExLgHFbIce+PLCuV1BB26Z4jNOQdd04p8bdfKNwe+A8AvWuZb+10x4jzEtbYDLBBlowjVr1W9TnjFhk6aIwQDxvsTnAqu568Q2ka6OR8qhgOcLyWZ/3nrXn,iv:t7UBLQAMBdy9UfmpLJZIJBiKk3B5lQftWqoWOF8bfyw=,tag:zTab5HDdMFgfBdyWVU3F6w==,type:str]
    password: ENC[AES256_GCM,data:vVBMpdf9h4o4rDjg0I/HkA==,iv:dIzjYWR4R4G9gk05yPskdvu1HOn21hpCC6LvKH3Yeyk=,tag:6ydARMQh7+3aSlQXsnlvKA==,type:str]
    postgres-password: ENC[AES256_GCM,data:6wxPH9nVav2ZY82QBT/pXw==,iv:Aj3WHwtZGatg5oFz/MhMK8Mf6avt1fc04RWjRHb1vew=,tag:XJQ6ygrDzVaq8QtCkaUsZA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: coder-db
    namespace: coder
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-07-14T22:22:55Z"
    mac: ENC[AES256_GCM,data:63LPUOxNTBSV2wHr2QXOD52rf44PwzP640hjSv8gA59uLnddCAKmnz7b++SSQCLB729HjcJDJXsGAamVIy6fE1doga284Llfi/SVY71Y+ffupgnwK7FEDMfced/l3bTXvOmUxRxDF/UdC8mgKusXgJT2CE0VVU1UyqAMDYviVwI=,iv:9I1VdqG0Rc/oGS+YqXWdxrEo6UOk2PKp0OpdzQqHLtM=,tag:QUSE7b1RIaPTsT5XFgMFKQ==,type:str]
    pgp:
        - created_at: "2023-07-14T22:22:54Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAx4MM/7fP/y8ARAAlOnDAtO9ANQ769G8YZ3HqTfMrTb1sRK3N1PDjtxHrRnY
            1UM2lwk3YQoheoS0GjnZW5j28iNqWsO7DswStHYjiIFHIq0//Dacn8tbq6Qjwa6E
            YE5jXDqPaLnBcyBqHHg9xadMxMAnagzql4JusBPzLoo79CfRpfEmWRjGCjs2PbE3
            j9S8zuevfKbkS/vog5J0KzlJ7b3FimZISYMDC76K6bC8v5tMBgVqhTcrcEqeag5k
            pPsh/3DRPIwgHm20Qw6gCNFK/D3DUhUK8oBu0hoRkRCfdrqoHCZWwL3DllpF9o1b
            ZFwAjE1Tht000OsHMVS82JGztRDkfT1yGBbbOi6+JOwyO/LpwMTiD2Lc6GLzBmw+
            R5fKoUWuUBuAZ0mq73WPEvJ2PICfxzZQL15dftKiYUM1Lkui1Z3Gx7MMylwa5BAg
            NoT4c9HT3Yp8zNjwkWPMVcogWYLdVK6GvSz/ocbsB2N/zEpotcQllvxf48ocxyuB
            f/LG6nMlH0nSmu3mcMr0Z1sLsIhqamP4kdwms+cisIUeJXQacE0m/ovmZuHgc8i/
            SogHenTSH+Ro7GGesAEyrEqPCTrdhpzfvpalILKT3j/G5kEyqsrMfGFPs9r+Pzd1
            I6HzzlROcCfT2AZ7BaXtCRT/2qvRj3vvPXV+R9G2fhSuzDjNOFmPASxJKHpH55XU
            aAEJAhCPI8//YoWEjEZDjKYPbq9J95aawOXJuwwMLgDb5F1PrI13iX1ljehZ19H+
            DhUKCrOU3Uu072gpcrt/h07TF8Jljz9sUyt6iRjjR/xRcOZXFFm9HdKdt0S94ihH
            SPYAvkdfN70d
            =uTeO
            -----END PGP MESSAGE-----
          fp: 1EE79B3DA3C67B0204A9CDA39100B3510A99E0DC
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
