apiVersion: v1
data:
    dburl: ENC[AES256_GCM,data:miBFRJo+VnlOg6VlwEL45AMZKmXev3pwX6TrdrmkF+V7w0ojm6xwdgPmtkdJ9/nW6swKYnYQRgSycLzn5ZmFRQSKl8SpBGelNfoaSdD03W/6NhQcWrWh9kriT0gwqc/DlnypkZfkTLKZ6YrTdZTopEGATZ/pUX1XU62TZVBe/9LFsJxnRjhbZg==,iv:DaJZrbEn4ZiLfHN32CmogSzr3yiUbkWu5t8Kn5xvQb4=,tag:xXeRbMBglhQ9+VNoOBgEZQ==,type:str]
    password: ENC[AES256_GCM,data:KrLJ7xNMURP0xbGCXSWwYA==,iv:VKCfSm54rav6v0SyGkUSbdArp/IRUi6qRAMQsPUvXqU=,tag:lVhxkLJA9Zr6ild1bbNEKA==,type:str]
    postgres-password: ENC[AES256_GCM,data:W8bpI4JkSmLxYlalvbHfbQ==,iv:9tA7dIQeLWg7OBAm6DeaIsdRhIBMmpijt9jZagfbHPg=,tag:t+zmnudqN6QU5Wswqjm0gQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: coder-db
    namespace: coder
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-07-14T21:53:47Z"
    mac: ENC[AES256_GCM,data:q/BJYthbUtU4PnT6xWABGNfA0h5vm5JVUUo3SGTiuNUL5AONsYQ42KZymO9qnOdsVprv5rtpJiX3zcHf7f1axOpbEQcZr4cxxlSNku2gL4GcNwRPLcuZuJ777rwDNcSbWSpq7HNJS1C2HsaYIKrsna53/AH7i4nHGil86ao+M6U=,iv:1cz44UZ1qxwQWUmt3Wg6U2daZhV2T/1M7PDUUKStdgw=,tag:uC90RxRZA5pbPOxALradTQ==,type:str]
    pgp:
        - created_at: "2023-07-14T21:53:47Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAx4MM/7fP/y8AQ//SnjKvDaw5/2Vstjrokl+TX/bdCskYsTLm6OZSdtEjry1
            4ZIDuCgkPfuxlJaeyOL0XBtT5b2daGgAOn5/VfPFldOrqrrNsekVFGcBNE07d4bV
            7RGJOHEYJ0HoNFQLPqHb1qMEXnitPW1sPg/1Q9QaT25WX7hcql5gGSP0QkKQjaOZ
            oUAkT8TZtBv8qk/IDVa1yrPwyNg7a07852c4uc1rbFdP86JYadxw50Qrm0svmBQv
            xv9Ddth7Z0oyktLzkd1BkiGU7MhQHmyxgqRnJulGUaKbSWzrTSOqaDt5LIHZIGsT
            WdTBDt7Vd2DxbkeLGWg2MomO2PKLoIiW5+Fy1X43FW9BJ3/KL54i9wlwVId8relf
            P4r957k5urFqykzrLmSZPd7vtV7D5tWrApVn9F0cFJSSXquTsA2bj4hIQ/ACzEHI
            Hxmp2ardB+MwN2AgcYGHR425mE2d9wJJCyHgXDQT89AulhJA+Ext1SGTCRK5oT72
            XAISc29LA/wW8W60rDhYmPIQ7PWCWmuPJX0bs+roDmOadvqDs8r7FZWm3ExlaC+u
            TAeJ4PmtqPZPDT6+sA7iKzOTxf+0qapEnz95q9Bz9RfB/tqvRkLd7A4JFwX/oLXK
            nu0E/lnqSUP58F28GlKT9UDZ7R9QjwlEGtvTXaVL1fW0dvi67IUvlkUxdh8ilGzU
            aAEJAhDoLBSGJeAqGPdPkbQD51RKwAC9k+TJ6uTQQAy1AIie9/FbmqZYcGSyKUOl
            8YCrmhGpFdPgsxlUyY6WA66oJXNHc2l9/OpUy/Gy1wqQ70+1u41g7uszFnJVzvFN
            AUBPsEr7/lzj
            =Yd1V
            -----END PGP MESSAGE-----
          fp: 1EE79B3DA3C67B0204A9CDA39100B3510A99E0DC
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
