# Warning  error  52s (x2 over 5m1s)  helm-controller  reconciliation failed: Helm install failed: rendered manifests contain a resource that already exists. Unable to continue with install: Ingress "coder" in namespace "coder" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "coder-coder"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "coder"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/server-snippets: |
      location / {
      proxy_set_header Upgrade $http_upgrade;
      proxy_http_version 1.1;
      proxy_set_header X-Forwarded-Host $http_host;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_set_header Host $host;
      proxy_set_header Connection "upgrade";
      proxy_cache_bypass $http_upgrade;
      }
  name: coder
  namespace: coder
spec:
  ingressClassName: nginx
  rules:
    - host: space.sharing.io
      http:
        paths:
          - backend:
              service:
                name: coder
                port:
                  name: http
            path: /
            pathType: Prefix
    - host: "*.sharing.io"
      http:
        paths:
          - backend:
              service:
                name: coder
                port:
                  name: http
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - space.sharing.io
        - "*.sharing.io"
---
