apiVersion: v1
data:
    gitauth-id: ENC[AES256_GCM,data:2DtDncHgPS2eh/xZ4mw8jbtIpUHoyaoZUA28eA==,iv:5QODcLORlXIUtoCR0QAp1gFlFheS1z4P4da9SAgyoEo=,tag:8lPPeZ49QFF4F/P9pZnM5A==,type:str]
    gitauth-secret: ENC[AES256_GCM,data:UZLtpTKZ3IOz5NtUctPDaPiQeCeK9QV+9S+HnMAvXM+NOTBZKLlT99wVpEFaA/6JzYEN0BzPrPg=,iv:aE7ZSQKpHvLnXBhkS754LgKL9JztrWoZLGGA8sGqcAM=,tag:hekywoCn1W2sPr2LYboEXw==,type:str]
    github-token: ENC[AES256_GCM,data:0i8LMjoEGm2pGLxMAPdhJ7J+HyRfYz/C3Mcs8uDQ/5zjaLnlgmKw2P942pSovI3clV0ZYqvx9Z8V3NK+qfLSwW3N0jWTiVravoMqkrBG7MUnt5t7G9mvwQXbrFhzF1p3+ivz+klUgRMqsXXn1j3dQy0qTyJQARnGJOZDAw==,iv:LzsLoy6BHFvHENFSS237DmwAsIvoVEwL15wzal8b9yU=,tag:WbpVVnkyWtNsud0/W+lYig==,type:str]
    metal-auth-token: ENC[AES256_GCM,data:tJMxIOAe9GwU7LK0tLNBtWRKPBnn+PG+G13I35uU23Iero4dgTcKLt25OjI=,iv:kFtgQaMsdlvpLUysUEjxA4txMp6rcJkAHxgTH3UDBHM=,tag:LZ1PqF7lThDAkzki6bJO4g==,type:str]
    oauth2-id: ENC[AES256_GCM,data:OltsU0sTwp4RNNAkE43fq39j6Mp5e5dsglrQMA==,iv:/PCzk6yqxvPTANY57prUfh9c8t5YPtVUNG0mdL0gh14=,tag:gM+EkGo8zuOZyUOwdFGZuQ==,type:str]
    oauth2-secret: ENC[AES256_GCM,data:biSuV8O8YQM10n3sjI12LpjL7ndgFi6Xm+6D7x6WSJFvWKQXQTQqMBYT/k+wYVD3lWC6kdGyG3k=,iv:ER5d6leiXPfA5oziGpr+rnZik7UpBf1jZeZBVkCkwTA=,tag:/AuMlQq8Q79ABKK09lIUTQ==,type:str]
    pdns-api-key: ENC[AES256_GCM,data:9PoaX/JZ1XaLATCMrcgKFTE82xsy3mDVO6ajfA==,iv:YDLYmzIcYDIyEF51dTIB22oyaKjsSRlfhJz77samFgk=,tag:VNGbKkgF2ttOqnXM5/M4iw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: coder
    namespace: coder
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-07-14T21:46:35Z"
    mac: ENC[AES256_GCM,data:zMLdMHcNwOjN7s8T/1VY/dmnNLPIEqxIubuZBAuUELnw6wNfVgTQbzZJx69YNYfcfqHu5i706nOgEXOBBNCPpt2WJwjP5OXMIVYHlkrNGLv9wAEAvz8jA8h7JQU7rop7XTP/YjN5VRW67lhNzng9tzAL8bnguUedStmViACEA2s=,iv:gFBV10GsqI79b0WDJaN6R/kAPd1+ock04VpmMENOGew=,tag:UrhZjZbSrEM5FPn3ruicfw==,type:str]
    pgp:
        - created_at: "2023-07-14T21:46:35Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAx4MM/7fP/y8AQ/9EowlaNh2vVOqhLTZ7Oy1JjfUCZ/smcbtfkQiiBl+6h4u
            BaP2eGfLmagOc9UFOCwJQ25VPGnRYwRnmEHq8/FH8mdxFVthO9ChLNZDbvVTPQOk
            80teHrufKsjtHY9j4SCcC6/NlVnFj6rg1ISUSeBdYA38UZZomVrUwKSazfn/vwCK
            r4N7kyOJuF1YaduS8af3T7G6OqiIw0EOFNIPd/CMZX9qAhcmKq1WsHIPlRgmyilh
            lmUiDpWzHSuI3IvPG3ik5N7tl1LSDq2GQQZH6gqEUP20X5cTOwbwtJnVdHJLqy88
            /EgfpuJzsgS4mDZ3x+ie4QGdEDnvLjAy2VcuYxNModrJVM53niqklqrt6Ww9PrxJ
            n7r3+9WCJpIPr0QtGpr0t0o2Ba2zYfWVmdYdxXPMVwHn0vqZEjUen6G7LqDJf77g
            GIjizEz0TAQKJEGQ2SDD+kZDPjwtBjT5709UH3E1641sH8cPgrCc5D1DDZe3cDlo
            H7nWGG4ik/1Nk1I7gowM9PCAq3iuRx4Ph+JK4kGpKz4Rwgx5eZ4lJAXqJxak/b9+
            ws/LVwj0EYq/RBitWFg0U7MnPdPITKi2J+6Lm11uwU8DgnG1cmFX6V36uJRuyHrJ
            V9Sp/AX1yDj1DMJNFk4qnd0caFmfnf4/PSZi2oOlk+bjd5WJJDf7FAJeiiMHTBTU
            aAEJAhBhxKsgQE+4CZgap3iJarXouEn9qVfImVmoClsCa9inubDLrv++FN4aiQS2
            nOEWf2fP3DbYdVe2eT+7I3HO4KMDb+C7ai4xSY29EQZPUoZmHMm+iQN5dm/D3Iqa
            XUwwj9j4jzyf
            =VWgJ
            -----END PGP MESSAGE-----
          fp: 1EE79B3DA3C67B0204A9CDA39100B3510A99E0DC
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
